url: "https://jkosem.github.io/jk-portfolio/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Jim Kosem: Design, strategy & research" # the name of your site, e.g. ACME Corp.

theme:

exclude:
  - README.md
  - .gitignore
